create extension if not exists btree_gist;

create table if not exists profiles (
  user_id uuid primary key,
  email text not null unique,
  full_name text null,
  role text not null default 'viewer' check (role in ('admin', 'viewer')),
  active boolean not null default true,
  approval_status text not null default 'pending' check (approval_status in ('pending', 'approved', 'rejected')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table profiles
  add column if not exists role text not null default 'viewer',
  add column if not exists active boolean not null default true,
  add column if not exists approval_status text not null default 'pending';

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'profiles_role_check'
  ) then
    alter table profiles
      add constraint profiles_role_check check (role in ('admin', 'viewer'));
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'profiles_approval_status_check'
  ) then
    alter table profiles
      add constraint profiles_approval_status_check check (approval_status in ('pending', 'approved', 'rejected'));
  end if;
end $$;

create index if not exists profiles_role_idx on profiles (role);
create index if not exists profiles_approval_status_idx on profiles (approval_status);

create table if not exists planning_items (
  id bigint generated by default as identity primary key,
  created_by uuid references profiles(user_id) on delete set null,
  item_date date not null,
  start_time time not null,
  end_time time not null,
  shift text not null,
  level text not null,
  front text not null,
  category text not null check (category in ('actividad', 'interferencia')),
  item_type text not null,
  description text not null,
  notes text null,
  activity_group_id text not null,
  tracking_type text not null default 'programado' check (tracking_type in ('programado', 'real')),
  client_mutation_id text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint planning_items_valid_range check (
    start_time <> end_time
    and (
      (
        shift = 'Dia'
        and start_time >= time '08:00'
        and end_time <= time '20:00'
        and end_time > start_time
      )
      or (
        shift = 'Noche'
        and (
          (start_time >= time '20:00' and end_time > start_time)
          or (start_time >= time '20:00' and end_time <= time '08:00')
          or (start_time <= time '08:00' and end_time <= time '08:00' and end_time > start_time)
        )
      )
    )
  )
);

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'planning_items'
      and column_name = 'subtype'
  ) and not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'planning_items'
      and column_name = 'item_type'
  ) then
    alter table planning_items rename column subtype to item_type;
  end if;

  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'planning_items'
      and column_name = 'title'
  ) and not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'planning_items'
      and column_name = 'description'
  ) then
    alter table planning_items rename column title to description;
  end if;
end $$;

alter table planning_items
  add column if not exists item_type text,
  add column if not exists description text,
  add column if not exists activity_group_id text,
  add column if not exists tracking_type text not null default 'programado',
  add column if not exists client_mutation_id text;

update planning_items
set activity_group_id = concat('legacy-', id)
where activity_group_id is null;

alter table planning_items
  alter column item_type set not null,
  alter column description set not null,
  alter column activity_group_id set not null;

alter table planning_items
  drop constraint if exists planning_items_valid_range;

alter table planning_items
  add constraint planning_items_valid_range
  check (
    start_time <> end_time
    and (
      (
        shift = 'Dia'
        and start_time >= time '08:00'
        and end_time <= time '20:00'
        and end_time > start_time
      )
      or (
        shift = 'Noche'
        and (
          (start_time >= time '20:00' and end_time > start_time)
          or (start_time >= time '20:00' and end_time <= time '08:00')
          or (start_time <= time '08:00' and end_time <= time '08:00' and end_time > start_time)
        )
      )
    )
  );

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'planning_items_tracking_type_check'
  ) then
    alter table planning_items
      add constraint planning_items_tracking_type_check check (tracking_type in ('programado', 'real'));
  end if;
end $$;

create index if not exists planning_items_date_idx on planning_items (item_date);
create index if not exists planning_items_shift_idx on planning_items (shift);
create index if not exists planning_items_front_idx on planning_items (front);
create index if not exists planning_items_category_idx on planning_items (category);
create index if not exists planning_items_group_idx on planning_items (activity_group_id);
create index if not exists planning_items_tracking_idx on planning_items (tracking_type);

create unique index if not exists planning_items_group_tracking_uidx
  on planning_items (activity_group_id, tracking_type);

create unique index if not exists planning_items_client_mutation_id_uidx
  on planning_items (client_mutation_id)
  where client_mutation_id is not null;

create table if not exists activity_execution_segments (
  id bigint generated by default as identity primary key,
  planning_item_id bigint references planning_items(id) on delete cascade,
  activity_group_id text not null,
  item_date date not null,
  shift text not null check (shift in ('Dia', 'Noche')),
  start_time time not null,
  end_time time not null,
  level text not null,
  front text not null,
  category text not null check (category in ('actividad', 'interferencia')),
  item_type text not null,
  description text not null,
  notes text null,
  segment_order integer not null default 1,
  client_mutation_id text null,
  created_by uuid references profiles(user_id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint activity_execution_segments_valid_range check (
    start_time <> end_time
    and (
      (
        shift = 'Dia'
        and start_time >= time '08:00'
        and end_time <= time '20:00'
        and end_time > start_time
      )
      or (
        shift = 'Noche'
        and (
          (start_time >= time '20:00' and end_time > start_time)
          or (start_time >= time '20:00' and end_time <= time '08:00')
          or (start_time <= time '08:00' and end_time <= time '08:00' and end_time > start_time)
        )
      )
    )
  )
);

alter table activity_execution_segments
  add column if not exists planning_item_id bigint references planning_items(id) on delete cascade,
  add column if not exists activity_group_id text,
  add column if not exists item_date date,
  add column if not exists shift text,
  add column if not exists start_time time,
  add column if not exists end_time time,
  add column if not exists level text,
  add column if not exists front text,
  add column if not exists category text,
  add column if not exists item_type text,
  add column if not exists description text,
  add column if not exists notes text,
  add column if not exists segment_order integer not null default 1,
  add column if not exists client_mutation_id text,
  add column if not exists created_by uuid references profiles(user_id) on delete set null,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

create index if not exists activity_execution_segments_group_idx
  on activity_execution_segments (activity_group_id);

create index if not exists activity_execution_segments_planning_item_idx
  on activity_execution_segments (planning_item_id);

create index if not exists activity_execution_segments_date_idx
  on activity_execution_segments (item_date);

create index if not exists activity_execution_segments_shift_idx
  on activity_execution_segments (shift);

create index if not exists activity_execution_segments_group_date_idx
  on activity_execution_segments (activity_group_id, item_date);

create unique index if not exists activity_execution_segments_group_order_uidx
  on activity_execution_segments (activity_group_id, segment_order);

create unique index if not exists activity_execution_segments_planning_item_order_uidx
  on activity_execution_segments (planning_item_id, segment_order);

create index if not exists activity_execution_segments_client_mutation_id_idx
  on activity_execution_segments (client_mutation_id)
  where client_mutation_id is not null;

alter table activity_execution_segments
  drop constraint if exists activity_execution_segments_no_overlap;

alter table activity_execution_segments
  add constraint activity_execution_segments_no_overlap
  exclude using gist (
    activity_group_id with =,
    tsrange(
      item_date::timestamp + start_time,
      item_date::timestamp + end_time + case when end_time <= start_time then interval '1 day' else interval '0 day' end,
      '[)'
    ) with &&
  );

comment on table activity_execution_segments is
  'Tramos de ejecucion real asociados a una actividad programada. Permite multiples segmentos por activity_group_id.';

comment on column activity_execution_segments.segment_order is
  'Orden del tramo real dentro de la misma actividad. Sirve para representar extensiones, pausas y cruces de turno.';

create table if not exists audit_logs (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references profiles(user_id) on delete set null,
  actor_email text null,
  action text not null,
  entity_type text not null,
  entity_id text null,
  before_data jsonb null,
  after_data jsonb null,
  metadata jsonb null,
  created_at timestamptz not null default now()
);

create index if not exists audit_logs_actor_user_id_idx on audit_logs (actor_user_id);
create index if not exists audit_logs_action_idx on audit_logs (action);
create index if not exists audit_logs_entity_idx on audit_logs (entity_type, entity_id);
create index if not exists audit_logs_created_at_idx on audit_logs (created_at desc);
