create table if not exists profiles (
  user_id uuid primary key,
  email text not null unique,
  full_name text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists planning_items (
  id bigint generated by default as identity primary key,
  created_by uuid references profiles(user_id) on delete set null,
  item_date date not null,
  start_time time not null,
  end_time time not null,
  shift text not null,
  level text not null,
  front text not null,
  category text not null check (category in ('actividad', 'interferencia')),
  subtype text not null,
  title text not null,
  notes text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint planning_items_valid_range check (
    start_time <> end_time
    and (
      (
        shift = 'Dia'
        and start_time >= time '08:00'
        and end_time <= time '19:00'
        and end_time > start_time
      )
      or (
        shift = 'Noche'
        and (
          (start_time >= time '20:00' and end_time > start_time)
          or (start_time >= time '20:00' and end_time <= time '07:00')
          or (start_time <= time '07:00' and end_time <= time '07:00' and end_time > start_time)
        )
      )
    )
  )
);

create index if not exists planning_items_date_idx on planning_items (item_date);
create index if not exists planning_items_shift_idx on planning_items (shift);
create index if not exists planning_items_front_idx on planning_items (front);
create index if not exists planning_items_category_idx on planning_items (category);
