create table if not exists profiles (
  user_id uuid primary key,
  email text not null unique,
  full_name text null,
  role text not null default 'viewer' check (role in ('admin', 'viewer')),
  active boolean not null default true,
  approval_status text not null default 'pending' check (approval_status in ('pending', 'approved', 'rejected')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table profiles
  add column if not exists role text not null default 'viewer',
  add column if not exists active boolean not null default true,
  add column if not exists approval_status text not null default 'pending';

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'profiles_role_check'
  ) then
    alter table profiles
      add constraint profiles_role_check check (role in ('admin', 'viewer'));
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'profiles_approval_status_check'
  ) then
    alter table profiles
      add constraint profiles_approval_status_check check (approval_status in ('pending', 'approved', 'rejected'));
  end if;
end $$;

create index if not exists profiles_role_idx on profiles (role);
create index if not exists profiles_approval_status_idx on profiles (approval_status);

create table if not exists planning_items (
  id bigint generated by default as identity primary key,
  created_by uuid references profiles(user_id) on delete set null,
  item_date date not null,
  start_time time not null,
  end_time time not null,
  shift text not null,
  level text not null,
  front text not null,
  category text not null check (category in ('actividad', 'interferencia')),
  subtype text not null,
  title text not null,
  notes text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint planning_items_valid_range check (
    start_time <> end_time
    and (
      (
        shift = 'Dia'
        and start_time >= time '08:00'
        and end_time <= time '20:00'
        and end_time > start_time
      )
      or (
        shift = 'Noche'
        and (
          (start_time >= time '20:00' and end_time > start_time)
          or (start_time >= time '20:00' and end_time <= time '08:00')
          or (start_time <= time '08:00' and end_time <= time '08:00' and end_time > start_time)
        )
      )
    )
  )
);

create index if not exists planning_items_date_idx on planning_items (item_date);
create index if not exists planning_items_shift_idx on planning_items (shift);
create index if not exists planning_items_front_idx on planning_items (front);
create index if not exists planning_items_category_idx on planning_items (category);
