create table if not exists planning_catalog_types (
  id bigint generated by default as identity primary key,
  category text not null check (category in ('actividad', 'interferencia')),
  slug text not null,
  label text not null,
  created_at timestamptz not null default now(),
  unique (category, slug),
  unique (category, label)
);

create table if not exists planning_catalog_details (
  id bigint generated by default as identity primary key,
  type_id bigint not null references planning_catalog_types(id) on delete cascade,
  label text not null,
  created_at timestamptz not null default now(),
  unique (type_id, label)
);

insert into planning_catalog_types (category, slug, label)
values
  ('actividad', 'unitaria', 'unitaria'),
  ('interferencia', 'mantencion', 'mantencion'),
  ('interferencia', 'seguridad', 'seguridad'),
  ('interferencia', 'operacional', 'operacional'),
  ('interferencia', 'geotecnica', 'geotecnica')
on conflict (category, slug) do update set label = excluded.label;

insert into planning_catalog_details (type_id, label)
select t.id, v.label
from planning_catalog_types t
join (
  values
    ('actividad', 'unitaria', 'Perforacion'),
    ('actividad', 'unitaria', 'Carguio'),
    ('actividad', 'unitaria', 'Tronadura'),
    ('actividad', 'unitaria', 'Fortificacion'),
    ('actividad', 'unitaria', 'Extraccion'),
    ('actividad', 'unitaria', 'Sostenimiento'),
    ('actividad', 'unitaria', 'Acuñadura'),
    ('actividad', 'unitaria', 'Levantamiento topografico'),
    ('interferencia', 'mantencion', 'Mantencion de equipo'),
    ('interferencia', 'mantencion', 'Mantencion electrica'),
    ('interferencia', 'mantencion', 'Mantencion mecanica'),
    ('interferencia', 'mantencion', 'Mantencion programada'),
    ('interferencia', 'seguridad', 'Bloqueo de area'),
    ('interferencia', 'seguridad', 'Inspeccion de seguridad'),
    ('interferencia', 'seguridad', 'Incidente operacional'),
    ('interferencia', 'seguridad', 'Restriccion por ventilacion'),
    ('interferencia', 'operacional', 'Falta de equipo'),
    ('interferencia', 'operacional', 'Falta de personal'),
    ('interferencia', 'operacional', 'Detencion de proceso'),
    ('interferencia', 'operacional', 'Interferencia por coordinacion'),
    ('interferencia', 'geotecnica', 'Caida de roca'),
    ('interferencia', 'geotecnica', 'Condicion geotecnica'),
    ('interferencia', 'geotecnica', 'Saneamiento de labor'),
    ('interferencia', 'geotecnica', 'Revision de sostenimiento')
) as v(category, type_slug, label)
  on t.category = v.category and t.slug = v.type_slug
on conflict (type_id, label) do nothing;
