create table if not exists planning_custom_fields (
  id bigint generated by default as identity primary key,
  slug text not null,
  label text not null,
  input_type text not null check (input_type in ('select', 'multi_select', 'number', 'text', 'date', 'boolean')),
  active boolean not null default true,
  required boolean not null default false,
  applies_to text not null default 'planned' check (applies_to in ('planned', 'actual', 'both')),
  sort_order integer not null default 100,
  config jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint planning_custom_fields_slug_not_blank check (btrim(slug) <> ''),
  constraint planning_custom_fields_label_not_blank check (btrim(label) <> ''),
  constraint planning_custom_fields_config_object check (jsonb_typeof(config) = 'object')
);

create unique index if not exists planning_custom_fields_slug_uidx
  on planning_custom_fields (slug);

create index if not exists planning_custom_fields_active_idx
  on planning_custom_fields (active);

create index if not exists planning_custom_fields_applies_to_idx
  on planning_custom_fields (applies_to);

create table if not exists planning_custom_field_options (
  id bigint generated by default as identity primary key,
  field_id bigint not null references planning_custom_fields(id) on delete cascade,
  value text not null,
  label text not null,
  active boolean not null default true,
  sort_order integer not null default 100,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint planning_custom_field_options_value_not_blank check (btrim(value) <> ''),
  constraint planning_custom_field_options_label_not_blank check (btrim(label) <> ''),
  constraint planning_custom_field_options_metadata_object check (jsonb_typeof(metadata) = 'object')
);

create unique index if not exists planning_custom_field_options_field_value_uidx
  on planning_custom_field_options (field_id, value);

create index if not exists planning_custom_field_options_field_id_idx
  on planning_custom_field_options (field_id);

create index if not exists planning_custom_field_options_active_idx
  on planning_custom_field_options (active);

create table if not exists planning_custom_field_values (
  id bigint generated by default as identity primary key,
  field_id bigint not null references planning_custom_fields(id) on delete cascade,
  planning_item_id bigint null references planning_items(id) on delete cascade,
  execution_segment_id bigint null references activity_execution_segments(id) on delete cascade,
  activity_group_id text null,
  option_id bigint null references planning_custom_field_options(id) on delete restrict,
  value_text text null,
  value_number numeric null,
  value_date date null,
  value_boolean boolean null,
  value_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint planning_custom_field_values_target_required check (
    planning_item_id is not null
    or execution_segment_id is not null
    or activity_group_id is not null
  ),
  constraint planning_custom_field_values_activity_group_not_blank check (
    activity_group_id is null or btrim(activity_group_id) <> ''
  ),
  constraint planning_custom_field_values_json_object check (jsonb_typeof(value_json) = 'object')
);

create index if not exists planning_custom_field_values_field_id_idx
  on planning_custom_field_values (field_id);

create index if not exists planning_custom_field_values_planning_item_id_idx
  on planning_custom_field_values (planning_item_id);

create index if not exists planning_custom_field_values_execution_segment_id_idx
  on planning_custom_field_values (execution_segment_id);

create index if not exists planning_custom_field_values_activity_group_id_idx
  on planning_custom_field_values (activity_group_id);

create index if not exists planning_custom_field_values_option_id_idx
  on planning_custom_field_values (option_id);

alter table if exists planning_custom_fields enable row level security;
alter table if exists planning_custom_field_options enable row level security;
alter table if exists planning_custom_field_values enable row level security;

drop policy if exists planning_custom_fields_select_approved on planning_custom_fields;
drop policy if exists planning_custom_field_options_select_approved on planning_custom_field_options;
drop policy if exists planning_custom_field_values_select_approved on planning_custom_field_values;

create policy planning_custom_fields_select_approved
  on planning_custom_fields
  for select
  to authenticated
  using (
    exists (
      select 1
      from profiles current_profile
      where current_profile.user_id = auth.uid()
        and current_profile.active = true
        and current_profile.approval_status = 'approved'
    )
  );

create policy planning_custom_field_options_select_approved
  on planning_custom_field_options
  for select
  to authenticated
  using (
    exists (
      select 1
      from profiles current_profile
      where current_profile.user_id = auth.uid()
        and current_profile.active = true
        and current_profile.approval_status = 'approved'
    )
  );

create policy planning_custom_field_values_select_approved
  on planning_custom_field_values
  for select
  to authenticated
  using (
    exists (
      select 1
      from profiles current_profile
      where current_profile.user_id = auth.uid()
        and current_profile.active = true
        and current_profile.approval_status = 'approved'
    )
  );

select pg_notify('pgrst', 'reload schema');
