create table if not exists assignment_types (
  id bigint generated by default as identity primary key,
  slug text not null,
  label text not null,
  description text null,
  active boolean not null default true,
  max_instances integer not null default 2,
  sort_order integer not null default 100,
  config jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint assignment_types_slug_not_blank check (btrim(slug) <> ''),
  constraint assignment_types_label_not_blank check (btrim(label) <> ''),
  constraint assignment_types_max_instances_check check (max_instances >= 1),
  constraint assignment_types_config_object check (jsonb_typeof(config) = 'object')
);

create unique index if not exists assignment_types_slug_uidx
  on assignment_types (slug);

create index if not exists assignment_types_active_idx
  on assignment_types (active);

create index if not exists assignment_types_sort_order_idx
  on assignment_types (sort_order);

create table if not exists assignment_fields (
  id bigint generated by default as identity primary key,
  assignment_type_id bigint not null references assignment_types(id) on delete restrict,
  slug text not null,
  label text not null,
  input_type text not null,
  active boolean not null default true,
  required boolean not null default false,
  sort_order integer not null default 100,
  config jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint assignment_fields_slug_not_blank check (btrim(slug) <> ''),
  constraint assignment_fields_label_not_blank check (btrim(label) <> ''),
  constraint assignment_fields_input_type_check check (
    input_type in ('text', 'number', 'date', 'boolean', 'select', 'multi_select')
  ),
  constraint assignment_fields_config_object check (jsonb_typeof(config) = 'object')
);

create unique index if not exists assignment_fields_type_slug_uidx
  on assignment_fields (assignment_type_id, slug);

create index if not exists assignment_fields_type_id_idx
  on assignment_fields (assignment_type_id);

create index if not exists assignment_fields_active_idx
  on assignment_fields (active);

create index if not exists assignment_fields_sort_order_idx
  on assignment_fields (sort_order);

create table if not exists assignment_field_options (
  id bigint generated by default as identity primary key,
  field_id bigint not null references assignment_fields(id) on delete restrict,
  value text not null,
  label text not null,
  active boolean not null default true,
  sort_order integer not null default 100,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint assignment_field_options_value_not_blank check (btrim(value) <> ''),
  constraint assignment_field_options_label_not_blank check (btrim(label) <> ''),
  constraint assignment_field_options_metadata_object check (jsonb_typeof(metadata) = 'object')
);

create unique index if not exists assignment_field_options_field_value_uidx
  on assignment_field_options (field_id, value);

create index if not exists assignment_field_options_field_id_idx
  on assignment_field_options (field_id);

create index if not exists assignment_field_options_active_idx
  on assignment_field_options (active);

alter table if exists assignment_types enable row level security;
alter table if exists assignment_fields enable row level security;
alter table if exists assignment_field_options enable row level security;

drop policy if exists assignment_types_select_approved on assignment_types;
drop policy if exists assignment_fields_select_approved on assignment_fields;
drop policy if exists assignment_field_options_select_approved on assignment_field_options;

create policy assignment_types_select_approved
  on assignment_types
  for select
  to authenticated
  using (
    exists (
      select 1
      from profiles current_profile
      where current_profile.user_id = auth.uid()
        and current_profile.active = true
        and current_profile.approval_status = 'approved'
    )
  );

create policy assignment_fields_select_approved
  on assignment_fields
  for select
  to authenticated
  using (
    exists (
      select 1
      from profiles current_profile
      where current_profile.user_id = auth.uid()
        and current_profile.active = true
        and current_profile.approval_status = 'approved'
    )
  );

create policy assignment_field_options_select_approved
  on assignment_field_options
  for select
  to authenticated
  using (
    exists (
      select 1
      from profiles current_profile
      where current_profile.user_id = auth.uid()
        and current_profile.active = true
        and current_profile.approval_status = 'approved'
    )
  );

select pg_notify('pgrst', 'reload schema');
