create table if not exists activity_execution_segments (
  id bigint generated by default as identity primary key,
  planning_item_id bigint not null references planning_items(id) on delete cascade,
  activity_group_id text not null,
  item_date date not null,
  shift text not null check (shift in ('Dia', 'Noche')),
  start_time time not null,
  end_time time not null,
  level text not null,
  front text not null,
  category text not null check (category in ('actividad', 'interferencia')),
  item_type text not null,
  description text not null,
  notes text null,
  segment_order integer not null default 1,
  created_by uuid references profiles(user_id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint activity_execution_segments_valid_range check (
    start_time <> end_time
    and (
      (
        shift = 'Dia'
        and start_time >= time '08:00'
        and end_time <= time '20:00'
        and end_time > start_time
      )
      or (
        shift = 'Noche'
        and (
          (start_time >= time '20:00' and end_time > start_time)
          or (start_time >= time '20:00' and end_time <= time '08:00')
          or (start_time <= time '08:00' and end_time <= time '08:00' and end_time > start_time)
        )
      )
    )
  )
);

alter table activity_execution_segments
  add column if not exists planning_item_id bigint references planning_items(id) on delete cascade;

alter table activity_execution_segments
  add column if not exists activity_group_id text;

alter table activity_execution_segments
  add column if not exists item_date date;

alter table activity_execution_segments
  add column if not exists shift text;

alter table activity_execution_segments
  add column if not exists start_time time;

alter table activity_execution_segments
  add column if not exists end_time time;

alter table activity_execution_segments
  add column if not exists level text;

alter table activity_execution_segments
  add column if not exists front text;

alter table activity_execution_segments
  add column if not exists category text;

alter table activity_execution_segments
  add column if not exists item_type text;

alter table activity_execution_segments
  add column if not exists description text;

alter table activity_execution_segments
  add column if not exists notes text;

alter table activity_execution_segments
  add column if not exists segment_order integer not null default 1;

alter table activity_execution_segments
  add column if not exists created_by uuid references profiles(user_id) on delete set null;

alter table activity_execution_segments
  add column if not exists created_at timestamptz not null default now();

alter table activity_execution_segments
  add column if not exists updated_at timestamptz not null default now();

create index if not exists activity_execution_segments_group_idx
  on activity_execution_segments (activity_group_id);

create index if not exists activity_execution_segments_planning_item_idx
  on activity_execution_segments (planning_item_id);

create index if not exists activity_execution_segments_date_idx
  on activity_execution_segments (item_date);

create index if not exists activity_execution_segments_shift_idx
  on activity_execution_segments (shift);

create index if not exists activity_execution_segments_group_date_idx
  on activity_execution_segments (activity_group_id, item_date);

create unique index if not exists activity_execution_segments_group_order_uidx
  on activity_execution_segments (activity_group_id, segment_order);

create unique index if not exists activity_execution_segments_planning_item_order_uidx
  on activity_execution_segments (planning_item_id, segment_order);

insert into activity_execution_segments (
  planning_item_id,
  activity_group_id,
  item_date,
  shift,
  start_time,
  end_time,
  level,
  front,
  category,
  item_type,
  description,
  notes,
  segment_order,
  created_by,
  created_at,
  updated_at
)
select
  planned.id,
  real.activity_group_id,
  real.item_date,
  real.shift,
  real.start_time,
  real.end_time,
  real.level,
  real.front,
  real.category,
  real.item_type,
  real.description,
  real.notes,
  1,
  real.created_by,
  real.created_at,
  real.updated_at
from planning_items real
join planning_items planned
  on planned.activity_group_id = real.activity_group_id
 and planned.tracking_type = 'programado'
where real.tracking_type = 'real'
on conflict do nothing;

comment on table activity_execution_segments is
  'Tramos de ejecucion real asociados a una actividad programada. Permite multiples segmentos por activity_group_id.';

comment on column activity_execution_segments.segment_order is
  'Orden del tramo real dentro de la misma actividad. Sirve para representar extensiones, pausas y cruces de turno.';
