create table if not exists planning_assignments (
  id bigint generated by default as identity primary key,
  planning_item_id bigint not null references planning_items(id) on delete cascade,
  assignment_type_id bigint not null references assignment_types(id) on delete restrict,
  instance_order integer not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint planning_assignments_instance_order_check check (instance_order >= 1),
  constraint planning_assignments_item_type_order_uidx unique (planning_item_id, assignment_type_id, instance_order)
);

create index if not exists planning_assignments_planning_item_id_idx
  on planning_assignments (planning_item_id);

create index if not exists planning_assignments_assignment_type_id_idx
  on planning_assignments (assignment_type_id);

create table if not exists planning_assignment_values (
  id bigint generated by default as identity primary key,
  assignment_id bigint not null references planning_assignments(id) on delete cascade,
  field_id bigint not null references assignment_fields(id) on delete restrict,
  option_id bigint null references assignment_field_options(id) on delete restrict,
  value_text text null,
  value_number numeric null,
  value_date date null,
  value_boolean boolean null,
  value_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint planning_assignment_values_json_object check (jsonb_typeof(value_json) = 'object')
);

create index if not exists planning_assignment_values_assignment_id_idx
  on planning_assignment_values (assignment_id);

create index if not exists planning_assignment_values_field_id_idx
  on planning_assignment_values (field_id);

create index if not exists planning_assignment_values_option_id_idx
  on planning_assignment_values (option_id);

alter table if exists planning_assignments enable row level security;
alter table if exists planning_assignment_values enable row level security;

drop policy if exists planning_assignments_select_approved on planning_assignments;
drop policy if exists planning_assignment_values_select_approved on planning_assignment_values;

create policy planning_assignments_select_approved
  on planning_assignments
  for select
  to authenticated
  using (
    exists (
      select 1
      from profiles current_profile
      where current_profile.user_id = auth.uid()
        and current_profile.active = true
        and current_profile.approval_status = 'approved'
    )
  );

create policy planning_assignment_values_select_approved
  on planning_assignment_values
  for select
  to authenticated
  using (
    exists (
      select 1
      from profiles current_profile
      where current_profile.user_id = auth.uid()
        and current_profile.active = true
        and current_profile.approval_status = 'approved'
    )
  );

create or replace function replace_planning_assignments(
  p_planning_item_id bigint,
  p_assignments jsonb
)
returns void
language plpgsql
set search_path = public
as $$
declare
  assignment_record jsonb;
  value_record jsonb;
  inserted_assignment_id bigint;
begin
  if jsonb_typeof(p_assignments) <> 'array' then
    raise exception 'p_assignments must be a JSON array';
  end if;

  delete from planning_assignments
  where planning_item_id = p_planning_item_id;

  for assignment_record in
    select value from jsonb_array_elements(p_assignments)
  loop
    insert into planning_assignments (
      planning_item_id,
      assignment_type_id,
      instance_order
    )
    values (
      p_planning_item_id,
      (assignment_record ->> 'assignment_type_id')::bigint,
      (assignment_record ->> 'instance_order')::integer
    )
    returning id into inserted_assignment_id;

    for value_record in
      select value from jsonb_array_elements(coalesce(assignment_record -> 'values', '[]'::jsonb))
    loop
      insert into planning_assignment_values (
        assignment_id,
        field_id,
        option_id,
        value_text,
        value_number,
        value_date,
        value_boolean,
        value_json
      )
      values (
        inserted_assignment_id,
        (value_record ->> 'field_id')::bigint,
        nullif(value_record ->> 'option_id', '')::bigint,
        value_record ->> 'value_text',
        nullif(value_record ->> 'value_number', '')::numeric,
        nullif(value_record ->> 'value_date', '')::date,
        nullif(value_record ->> 'value_boolean', '')::boolean,
        coalesce(value_record -> 'value_json', '{}'::jsonb)
      );
    end loop;
  end loop;
end;
$$;

revoke all on function replace_planning_assignments(bigint, jsonb) from public;
revoke all on function replace_planning_assignments(bigint, jsonb) from authenticated;
grant execute on function replace_planning_assignments(bigint, jsonb) to service_role;

select pg_notify('pgrst', 'reload schema');
