create table if not exists planning_levels (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  label text not null unique,
  created_at timestamptz not null default now()
);

insert into planning_levels (slug, label)
values
  ('nti', 'NTI'),
  ('nnm', 'NNM'),
  ('snv', 'SNV')
on conflict (slug) do update set label = excluded.label;
