create table if not exists audit_logs (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references profiles(user_id) on delete set null,
  actor_email text null,
  action text not null,
  entity_type text not null,
  entity_id text null,
  before_data jsonb null,
  after_data jsonb null,
  metadata jsonb null,
  created_at timestamptz not null default now()
);

create index if not exists audit_logs_actor_user_id_idx on audit_logs (actor_user_id);
create index if not exists audit_logs_action_idx on audit_logs (action);
create index if not exists audit_logs_entity_idx on audit_logs (entity_type, entity_id);
create index if not exists audit_logs_created_at_idx on audit_logs (created_at desc);

alter table if exists audit_logs enable row level security;
