create table if not exists operational_header_fields (
  id bigint generated by default as identity primary key,
  slug text not null,
  label text not null,
  input_type text not null check (input_type in ('text', 'select')),
  required boolean not null default false,
  active boolean not null default true,
  sort_order integer not null default 0,
  groupable boolean not null default false,
  filterable boolean not null default false,
  visible_in_gantt boolean not null default false,
  exportable boolean not null default true,
  legacy_column text null check (legacy_column is null or legacy_column in ('level', 'front')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint operational_header_fields_slug_not_blank check (btrim(slug) <> ''),
  constraint operational_header_fields_label_not_blank check (btrim(label) <> '')
);

create unique index if not exists operational_header_fields_slug_uidx
  on operational_header_fields (slug);

create index if not exists operational_header_fields_active_idx
  on operational_header_fields (active);

create index if not exists operational_header_fields_legacy_column_idx
  on operational_header_fields (legacy_column)
  where legacy_column is not null;

create table if not exists operational_header_field_options (
  id bigint generated by default as identity primary key,
  field_id bigint not null references operational_header_fields(id) on delete cascade,
  value text not null,
  label text not null,
  active boolean not null default true,
  sort_order integer not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint operational_header_field_options_value_not_blank check (btrim(value) <> ''),
  constraint operational_header_field_options_label_not_blank check (btrim(label) <> ''),
  constraint operational_header_field_options_metadata_object check (jsonb_typeof(metadata) = 'object')
);

create unique index if not exists operational_header_field_options_field_value_uidx
  on operational_header_field_options (field_id, value);

create index if not exists operational_header_field_options_field_id_idx
  on operational_header_field_options (field_id);

create index if not exists operational_header_field_options_active_idx
  on operational_header_field_options (active);

create table if not exists operational_header_option_dependencies (
  id bigint generated by default as identity primary key,
  field_id bigint not null references operational_header_fields(id) on delete cascade,
  option_id bigint not null references operational_header_field_options(id) on delete cascade,
  depends_on_field_id bigint not null references operational_header_fields(id) on delete cascade,
  depends_on_option_id bigint not null references operational_header_field_options(id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint operational_header_option_dependencies_no_self_option check (option_id <> depends_on_option_id)
);

create unique index if not exists operational_header_option_dependencies_option_dependency_uidx
  on operational_header_option_dependencies (option_id, depends_on_option_id);

create index if not exists operational_header_option_dependencies_field_id_idx
  on operational_header_option_dependencies (field_id);

create index if not exists operational_header_option_dependencies_depends_on_field_id_idx
  on operational_header_option_dependencies (depends_on_field_id);

create table if not exists operational_header_values (
  id bigint generated by default as identity primary key,
  field_id bigint not null references operational_header_fields(id) on delete cascade,
  activity_group_id text not null,
  planning_item_id bigint null references planning_items(id) on delete cascade,
  execution_segment_id bigint null references activity_execution_segments(id) on delete cascade,
  option_id bigint null references operational_header_field_options(id) on delete restrict,
  value_text text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint operational_header_values_activity_group_not_blank check (btrim(activity_group_id) <> ''),
  constraint operational_header_values_single_override_target check (
    not (planning_item_id is not null and execution_segment_id is not null)
  ),
  constraint operational_header_values_value_required check (
    option_id is not null
    or btrim(coalesce(value_text, '')) <> ''
  )
);

create index if not exists operational_header_values_field_id_idx
  on operational_header_values (field_id);

create index if not exists operational_header_values_activity_group_id_idx
  on operational_header_values (activity_group_id);

create index if not exists operational_header_values_planning_item_id_idx
  on operational_header_values (planning_item_id)
  where planning_item_id is not null;

create index if not exists operational_header_values_execution_segment_id_idx
  on operational_header_values (execution_segment_id)
  where execution_segment_id is not null;

create index if not exists operational_header_values_option_id_idx
  on operational_header_values (option_id)
  where option_id is not null;

create unique index if not exists operational_header_values_group_scope_uidx
  on operational_header_values (field_id, activity_group_id)
  where planning_item_id is null and execution_segment_id is null;

create unique index if not exists operational_header_values_planning_item_uidx
  on operational_header_values (field_id, planning_item_id)
  where planning_item_id is not null;

create unique index if not exists operational_header_values_execution_segment_uidx
  on operational_header_values (field_id, execution_segment_id)
  where execution_segment_id is not null;

insert into operational_header_fields (
  slug,
  label,
  input_type,
  required,
  active,
  sort_order,
  groupable,
  filterable,
  visible_in_gantt,
  exportable,
  legacy_column
)
values
  ('nivel', 'Nivel', 'select', true, true, 10, true, true, true, true, 'level'),
  ('frente', 'Frente', 'text', true, true, 20, true, true, true, true, 'front')
on conflict (slug) do update set
  label = excluded.label,
  input_type = excluded.input_type,
  required = excluded.required,
  active = excluded.active,
  sort_order = excluded.sort_order,
  groupable = excluded.groupable,
  filterable = excluded.filterable,
  visible_in_gantt = excluded.visible_in_gantt,
  exportable = excluded.exportable,
  legacy_column = excluded.legacy_column,
  updated_at = now();

insert into operational_header_field_options (
  field_id,
  value,
  label,
  active,
  sort_order
)
select
  field.id,
  planning_levels.slug,
  planning_levels.label,
  true,
  planning_levels.id::integer * 10
from planning_levels
join operational_header_fields field
  on field.slug = 'nivel'
on conflict (field_id, value) do update set
  label = excluded.label,
  active = excluded.active,
  sort_order = excluded.sort_order,
  updated_at = now();

insert into operational_header_values (
  field_id,
  activity_group_id,
  planning_item_id,
  option_id,
  value_text
)
select
  field.id,
  item.activity_group_id,
  item.id,
  option.id,
  item.level
from planning_items item
join operational_header_fields field
  on field.slug = 'nivel'
left join operational_header_field_options option
  on option.field_id = field.id
  and (
    lower(option.value) = lower(item.level)
    or lower(option.label) = lower(item.level)
  )
where btrim(coalesce(item.activity_group_id, '')) <> ''
  and btrim(coalesce(item.level, '')) <> ''
on conflict (field_id, planning_item_id) where planning_item_id is not null do update set
  activity_group_id = excluded.activity_group_id,
  option_id = excluded.option_id,
  value_text = excluded.value_text,
  updated_at = now();

insert into operational_header_values (
  field_id,
  activity_group_id,
  planning_item_id,
  value_text
)
select
  field.id,
  item.activity_group_id,
  item.id,
  item.front
from planning_items item
join operational_header_fields field
  on field.slug = 'frente'
where btrim(coalesce(item.activity_group_id, '')) <> ''
  and btrim(coalesce(item.front, '')) <> ''
on conflict (field_id, planning_item_id) where planning_item_id is not null do update set
  activity_group_id = excluded.activity_group_id,
  value_text = excluded.value_text,
  updated_at = now();

insert into operational_header_values (
  field_id,
  activity_group_id,
  execution_segment_id,
  option_id,
  value_text
)
select
  field.id,
  segment.activity_group_id,
  segment.id,
  option.id,
  segment.level
from activity_execution_segments segment
join operational_header_fields field
  on field.slug = 'nivel'
left join operational_header_field_options option
  on option.field_id = field.id
  and (
    lower(option.value) = lower(segment.level)
    or lower(option.label) = lower(segment.level)
  )
where btrim(coalesce(segment.activity_group_id, '')) <> ''
  and btrim(coalesce(segment.level, '')) <> ''
on conflict (field_id, execution_segment_id) where execution_segment_id is not null do update set
  activity_group_id = excluded.activity_group_id,
  option_id = excluded.option_id,
  value_text = excluded.value_text,
  updated_at = now();

insert into operational_header_values (
  field_id,
  activity_group_id,
  execution_segment_id,
  value_text
)
select
  field.id,
  segment.activity_group_id,
  segment.id,
  segment.front
from activity_execution_segments segment
join operational_header_fields field
  on field.slug = 'frente'
where btrim(coalesce(segment.activity_group_id, '')) <> ''
  and btrim(coalesce(segment.front, '')) <> ''
on conflict (field_id, execution_segment_id) where execution_segment_id is not null do update set
  activity_group_id = excluded.activity_group_id,
  value_text = excluded.value_text,
  updated_at = now();

alter table if exists operational_header_fields enable row level security;
alter table if exists operational_header_field_options enable row level security;
alter table if exists operational_header_option_dependencies enable row level security;
alter table if exists operational_header_values enable row level security;

drop policy if exists operational_header_fields_select_approved on operational_header_fields;
drop policy if exists operational_header_field_options_select_approved on operational_header_field_options;
drop policy if exists operational_header_option_dependencies_select_approved on operational_header_option_dependencies;
drop policy if exists operational_header_values_select_approved on operational_header_values;

create policy operational_header_fields_select_approved
  on operational_header_fields
  for select
  to authenticated
  using (
    exists (
      select 1
      from profiles current_profile
      where current_profile.user_id = auth.uid()
        and current_profile.active = true
        and current_profile.approval_status = 'approved'
    )
  );

create policy operational_header_field_options_select_approved
  on operational_header_field_options
  for select
  to authenticated
  using (
    exists (
      select 1
      from profiles current_profile
      where current_profile.user_id = auth.uid()
        and current_profile.active = true
        and current_profile.approval_status = 'approved'
    )
  );

create policy operational_header_option_dependencies_select_approved
  on operational_header_option_dependencies
  for select
  to authenticated
  using (
    exists (
      select 1
      from profiles current_profile
      where current_profile.user_id = auth.uid()
        and current_profile.active = true
        and current_profile.approval_status = 'approved'
    )
  );

create policy operational_header_values_select_approved
  on operational_header_values
  for select
  to authenticated
  using (
    exists (
      select 1
      from profiles current_profile
      where current_profile.user_id = auth.uid()
        and current_profile.active = true
        and current_profile.approval_status = 'approved'
    )
  );

select pg_notify('pgrst', 'reload schema');
