create table if not exists user_permissions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references profiles(user_id) on delete cascade,
  permission text not null,
  effect text not null check (effect in ('allow', 'deny')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint user_permissions_permission_not_blank check (btrim(permission) <> ''),
  constraint user_permissions_permission_check check (
    permission in (
      'records.view',
      'records.create',
      'records.edit',
      'records.delete',
      'catalog.view',
      'catalog.manage',
      'reports.view',
      'users.view',
      'users.manage',
      'audit.view',
      'operational_header.view',
      'operational_header.manage',
      'assignments.view',
      'assignments.manage'
    )
  ),
  constraint user_permissions_user_permission_uidx unique (user_id, permission)
);

create index if not exists user_permissions_user_id_idx on user_permissions (user_id);
create index if not exists user_permissions_permission_idx on user_permissions (permission);
create index if not exists user_permissions_effect_idx on user_permissions (effect);

alter table if exists user_permissions enable row level security;

drop policy if exists user_permissions_select_own_admin on user_permissions;

create policy user_permissions_select_own_admin
  on user_permissions
  for select
  to authenticated
  using (
    user_id = auth.uid()
    or exists (
      select 1
      from profiles current_profile
      where current_profile.user_id = auth.uid()
        and current_profile.role = 'admin'
        and current_profile.active = true
        and current_profile.approval_status = 'approved'
    )
  );

select pg_notify('pgrst', 'reload schema');
